<?php

namespace Database\Seeders;

use App\Models\Scorecard;
use App\Models\ScorecardHandicapHole;
use App\Models\ScorecardStrokeIndex;
use App\Models\ScorecardHoleHandicap;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ScorecardStokeIndexSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //         $table->unsignedBigInteger('scorecard_id');
        // $table->unsignedBigInteger('scorecard_hole_id');
        // $table->enum('gender', ['M', 'F'])->comment('M = Male, F = Female');
        // $table->unsignedSmallInteger('handicap_hole')->nullable()->default(null)->comment('Handicap for the hole, typically 1-18, null if not assigned');


        ScorecardStrokeIndex::insert([
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 1,
                'hole' => 1,
                'gender' => 'M',
                'handicap_hole' => 3,
                'scorecard_hole' => 1,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 2,
                'hole' => 2,
                'gender' => 'M',
                'handicap_hole' => 5,
                'scorecard_hole' => 2,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 3,
                'hole' => 3,
                'gender' => 'M',
                'handicap_hole' => 11,
                'scorecard_hole' => 3,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 4,
                'hole' => 4,
                'gender' => 'M',
                'handicap_hole' => 13,
                'scorecard_hole' => 4,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 5,
                'hole' => 5,
                'gender' => 'M',
                'handicap_hole' => 1,
                'scorecard_hole' => 5,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 6,
                'hole' => 6,
                'gender' => 'M',
                'handicap_hole' => 7,
                'scorecard_hole' => 6,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 7,
                'hole' => 7,
                'gender' => 'M',
                'handicap_hole' => 17,
                'scorecard_hole' => 7,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 8,
                'hole' => 8,
                'gender' => 'M',
                'handicap_hole' => 15,
                'scorecard_hole' => 8,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 9,
                'hole' => 9,
                'gender' => 'M',
                'handicap_hole' => 9,
                'scorecard_hole' => 9,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 10,
                'hole' => 10,
                'gender' => 'M',
                'handicap_hole' => 12,
                'scorecard_hole' => 10,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 11,
                'hole' => 11,
                'gender' => 'M',
                'handicap_hole' => 18,
                'scorecard_hole' => 11,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 12,
                'hole' => 12,
                'gender' => 'M',
                'handicap_hole' => 10,
                'scorecard_hole' => 12,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 13,
                'hole' => 13,
                'gender' => 'M',
                'handicap_hole' => 6,
                'scorecard_hole' => 13,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 14,
                'hole' => 14,
                'gender' => 'M',
                'handicap_hole' => 14,
                'scorecard_hole' => 14,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 15,
                'hole' => 15,
                'gender' => 'M',
                'handicap_hole' => 16,
                'scorecard_hole' => 15,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 16,
                'hole' => 16,
                'gender' => 'M',
                'handicap_hole' => 8,
                'scorecard_hole' => 16,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 17,
                'hole' => 17,
                'gender' => 'M',
                'handicap_hole' => 4,
                'scorecard_hole' => 17,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 18,
                'hole' => 18,
                'gender' => 'M',
                'handicap_hole' => 2,
                'scorecard_hole' => 18,
                'created_by' => 1,
            ],

            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 1,
                'hole' => 1,
                'gender' => 'F',
                'handicap_hole' => 3,
                'scorecard_hole' => 1,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 2,
                'hole' => 2,
                'gender' => 'F',
                'handicap_hole' => 7,
                'scorecard_hole' => 2,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 3,
                'hole' => 3,
                'gender' => 'F',
                'handicap_hole' => 13,
                'scorecard_hole' => 3,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 4,
                'hole' => 4,
                'gender' => 'F',
                'handicap_hole' => 9,
                'scorecard_hole' => 4,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 5,
                'hole' => 5,
                'gender' => 'F',
                'handicap_hole' => 1,
                'scorecard_hole' => 5,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 6,
                'hole' => 6,
                'gender' => 'F',
                'handicap_hole' => 15,
                'scorecard_hole' => 6,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 7,
                'hole' => 7,
                'gender' => 'F',
                'handicap_hole' => 11,
                'scorecard_hole' => 7,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 8,
                'hole' => 8,
                'gender' => 'F',
                'handicap_hole' => 17,
                'scorecard_hole' => 8,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 9,
                'hole' => 9,
                'gender' => 'F',
                'handicap_hole' => 5,
                'scorecard_hole' => 9,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 10,
                'hole' => 10,
                'gender' => 'F',
                'handicap_hole' => 5,
                'scorecard_hole' => 10,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 11,
                'hole' => 11,
                'gender' => 'F',
                'handicap_hole' => 18,
                'scorecard_hole' => 11,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 12,
                'hole' => 12,
                'gender' => 'F',
                'handicap_hole' => 14,
                'scorecard_hole' => 12,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 13,
                'hole' => 13,
                'gender' => 'F',
                'handicap_hole' => 4,
                'scorecard_hole' => 13,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 14,
                'hole' => 14,
                'gender' => 'F',
                'handicap_hole' => 12,
                'scorecard_hole' => 14,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 15,
                'hole' => 15,
                'gender' => 'F',
                'handicap_hole' => 16,
                'scorecard_hole' => 15,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 16,
                'hole' => 16,
                'gender' => 'F',
                'handicap_hole' => 6,
                'scorecard_hole' => 16,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 17,
                'hole' => 17,
                'gender' => 'F',
                'handicap_hole' => 8,
                'scorecard_hole' => 17,
                'created_by' => 1,
            ],
            [
                'scorecard_id' => 1,
                'scorecard_hole_id' => 18,
                'hole' => 18,
                'gender' => 'F',
                'handicap_hole' => 2,
                'scorecard_hole' => 18,
                'created_by' => 1,
            ]
        ]);
    }
}
