<?php

namespace Database\Seeders;

use App\Models\Scorecard;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TournamentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::unprepared("
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (1,'ALL SENIORS 2025',NULL,'2025-08-30','2025-08-30',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 12:54:43','2025-11-07 12:54:43');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (2,'BARKADAHAN 2024 - JUNE',NULL,'2024-06-21','2024-06-29',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 13:52:22','2025-11-07 13:52:22');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (3,'BARKADAHAN 2024 - JULY',NULL,'2024-07-06','2024-07-22',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 13:56:56','2025-11-07 13:56:56');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (4,'BARKADAHAN 2024 - AUGUST',NULL,'2024-08-03','2024-08-04',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 13:59:04','2025-11-07 13:59:04');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (5,'BARKADAHAN 2025',NULL,'2025-05-25','2025-08-09',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:00:56','2025-11-07 14:00:56');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (6,'CLUB CHAMP Q1 2024',NULL,'2024-01-06','2024-01-13',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:02:39','2025-11-07 14:02:39');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (7,'CLUB CHAMP Q1 2025',NULL,'2024-10-05','2024-10-16',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:07:15','2025-11-07 14:07:15');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (8,'DCT 2024',NULL,'2024-03-21','2024-03-24',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:09:08','2025-11-07 14:09:08');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (9,'DCT 2025',NULL,'2025-02-19','2025-02-22',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:10:16','2025-11-07 14:10:16');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (10,'DCT 2025 - SP',NULL,'2025-02-19','2025-02-22',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:11:18','2025-11-07 14:11:18');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (11,'INTRA 2024',NULL,'2024-11-23','2024-11-23',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:14:42','2025-11-07 14:14:42');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (12,'INTRA 2025',NULL,'2025-04-26','2025-04-27',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:16:04','2025-11-07 14:16:04');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (13,'PRESCUP 2024',NULL,'2024-09-15','2024-09-15',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:17:04','2025-11-07 14:17:04');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (14,'PRESCUP 2025',NULL,'2025-09-14','2025-09-14',NULL,NULL,NULL,NULL,'AVG(SELECTED_DIFFERENTIALS) * 0.96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-07 14:17:59','2025-11-07 14:17:59');
            INSERT INTO `tournaments` (`tournament_id`,`tournament_name`,`tournament_desc`,`tournament_start`,`tournament_end`,`score_diff_start_date`,`score_diff_end_date`,`recent_scores_count`,`scores_to_average`,`tournament_handicap_formula_1`,`tournament_handicap_formula_2`,`tournament_handicap_formula_3`,`tournament_handicap_formula_4`,`tournament_handicap_formula_desc`,`course_handicap_formula_desc`,`handicap_score_differential_config`,`cancelled_at`,`cancelled_by`,`cancel_reason`,`remarks`,`status`,`scorecard_id`,`whs_handicap_import_id`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (15,'All Juniors 2025',NULL,'2025-08-19','2025-08-19',NULL,NULL,NULL,NULL,'MIN(LOCAL_HANDICAP_INDEX, WHS_HANDICAP_INDEX)','WHS_HANDICAP_INDEX * 0.8','LOCAL_HANDICAP_INDEX',NULL,NULL,NULL,'{\"3\": {\"max\": \"3\", \"min\": \"3\", \"count\": \"1\", \"method\": \"LOWEST\", \"adjustment\": \"-2.0\"}, \"4\": {\"max\": \"4\", \"min\": \"4\", \"count\": \"1\", \"method\": \"LOWEST\", \"adjustment\": \"-1.0\"}, \"5\": {\"max\": \"5\", \"min\": \"5\", \"count\": \"1\", \"method\": \"LOWEST\", \"adjustment\": \"0\"}, \"6\": {\"max\": \"6\", \"min\": \"6\", \"count\": \"2\", \"method\": \"AVERAGE_OF_LOWEST\", \"adjustment\": \"-1.0\"}, \"7\": {\"max\": \"8\", \"min\": \"7\", \"count\": \"2\", \"method\": \"AVERAGE_OF_LOWEST\", \"adjustment\": \"0\"}, \"9\": {\"max\": \"11\", \"min\": \"9\", \"count\": \"3\", \"method\": \"AVERAGE_OF_LOWEST\", \"adjustment\": \"0\"}, \"12\": {\"max\": \"14\", \"min\": \"12\", \"count\": \"4\", \"method\": \"AVERAGE_OF_LOWEST\", \"adjustment\": \"0\"}, \"15\": {\"max\": \"16\", \"min\": \"15\", \"count\": \"5\", \"method\": \"AVERAGE_OF_LOWEST\", \"adjustment\": \"0\"}, \"17\": {\"max\": \"18\", \"min\": \"17\", \"count\": \"6\", \"method\": \"AVERAGE_OF_LOWEST\", \"adjustment\": \"0\"}, \"19\": {\"max\": \"19\", \"min\": \"19\", \"count\": \"7\", \"method\": \"AVERAGE_OF_LOWEST\", \"adjustment\": \"0\"}, \"20\": {\"max\": \"20\", \"min\": \"20\", \"count\": \"8\", \"method\": \"AVERAGE_OF_LOWEST\", \"adjustment\": \"0\"}}',NULL,NULL,NULL,NULL,'active',NULL,NULL,1,NULL,'2025-11-15 14:24:25','2025-11-15 14:24:25');


            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (1,1,1,5,1,1,NULL,'2025-11-07 12:54:43','2025-11-07 12:54:43');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (2,1,2,4,1,1,NULL,'2025-11-07 12:54:43','2025-11-07 12:54:43');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (3,2,1,1,1,1,NULL,'2025-11-07 13:52:22','2025-11-07 13:52:22');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (4,2,2,2,1,1,NULL,'2025-11-07 13:52:22','2025-11-07 13:52:22');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (5,3,1,3,1,1,NULL,'2025-11-07 13:56:56','2025-11-07 13:56:56');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (6,3,2,4,1,1,NULL,'2025-11-07 13:56:56','2025-11-07 13:56:56');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (7,4,1,3,1,1,NULL,'2025-11-07 13:59:04','2025-11-07 13:59:04');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (8,5,1,3,1,1,NULL,'2025-11-07 14:00:56','2025-11-07 14:00:56');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (9,5,2,4,1,1,NULL,'2025-11-07 14:00:56','2025-11-07 14:00:56');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (10,6,1,1,1,1,NULL,'2025-11-07 14:02:39','2025-11-07 14:02:39');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (11,6,2,2,1,1,NULL,'2025-11-07 14:02:39','2025-11-07 14:02:39');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (12,7,1,3,1,1,NULL,'2025-11-07 14:07:15','2025-11-07 14:07:15');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (13,7,2,4,1,1,NULL,'2025-11-07 14:07:15','2025-11-07 14:07:15');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (14,8,1,1,1,1,NULL,'2025-11-07 14:09:08','2025-11-07 14:09:08');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (15,8,2,2,1,1,NULL,'2025-11-07 14:09:08','2025-11-07 14:09:08');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (16,9,1,3,1,1,NULL,'2025-11-07 14:10:16','2025-11-07 14:10:16');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (17,9,2,4,1,1,NULL,'2025-11-07 14:10:16','2025-11-07 14:10:16');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (18,10,1,3,1,1,NULL,'2025-11-07 14:11:18','2025-11-07 14:11:18');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (19,10,2,4,1,1,NULL,'2025-11-07 14:11:18','2025-11-07 14:11:18');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (20,11,1,3,1,1,NULL,'2025-11-07 14:14:42','2025-11-07 14:14:42');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (21,11,2,4,1,1,NULL,'2025-11-07 14:14:42','2025-11-07 14:14:42');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (22,12,1,3,1,1,NULL,'2025-11-07 14:16:04','2025-11-07 14:16:04');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (23,12,2,4,1,1,NULL,'2025-11-07 14:16:04','2025-11-07 14:16:04');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (24,13,1,3,1,1,NULL,'2025-11-07 14:17:04','2025-11-07 14:17:04');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (25,13,2,4,1,1,NULL,'2025-11-07 14:17:04','2025-11-07 14:17:04');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (26,14,1,5,1,1,NULL,'2025-11-07 14:17:59','2025-11-07 14:17:59');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (27,14,2,4,1,1,NULL,'2025-11-07 14:17:59','2025-11-07 14:17:59');
            INSERT INTO `tournament_courses` (`tournament_course_id`,`tournament_id`,`course_id`,`scorecard_id`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (28,15,2,4,1,1,NULL,'2025-11-15 14:24:25','2025-11-15 14:24:25');

            INSERT INTO `divisions` (`division_id`,`division_name`,`division_desc`,`division_type`,`division_sex`,`division_participant_type`,`tournament_id`,`age_min`,`age_max`,`handicap_index_min`,`handicap_index_max`,`remarks`,`active`,`created_by`,`updated_by`,`created_at`,`updated_at`) VALUES (1,'All Juniors 2025',NULL,'regular','X','mixed',15,NULL,NULL,NULL,NULL,NULL,1,1,NULL,'2025-11-15 14:24:25',NULL);

        ");
    }
}
